### ISSUE TITLE
Night Vision Control

### ISSUE THREAD

**Issue by ccomkhj** [fronzbot/blinkpy#639]
![image](https://user-images.githubusercontent.com/15991517/197843086-2fe39647-498b-4f95-84a6-3104e6c4e1a2.png)

How can I change the night vision mode using blinkpy?

It will be very helpful if I can control Night-Vision's control and IR intensity.

**Comment by davidahmed** [comment]
Interesting issue. I tried to solve this as well but failed; could be very helpful for my use case. Anyone any idea/ steps I could take to solve it?
