### ISSUE TITLE
Wired Flood Light control

### ISSUE THREAD

**Issue by morozsm** [fronzbot/blinkpy#797]
Would be nice to have a possibility to control Blink Wired Flood Light with blinkpy

**Additional context**
Looks like, original protocol hack doesn't include floodlight API, but it looks like that it was hacked and implemented here: https://www.drdsnell.com/projects/hubitat/drivers/BlinkChild-WiredFloodlight.groovy

**Comment by Rosi2143** [comment]
Hi @morozsm,

I believe this is already covered by issue #583.
