### ISSUE TITLE
Cant get save_recent_clips automation to work.

### ISSUE THREAD

**Issue by blthlt** [fronzbot/blinkpy#940]
**Describe the bug**
I'm getting an error when trying to setup and automation to grab all recent clips.  The automation doesn't appear to run.  I can use the blink.save_video to get the last video just fine but the blink.save_recent_clips does not.

![image](https://github.com/fronzbot/blinkpy/assets/479263/9bd04646-4425-45f5-b0d6-aaa869d14ece)

**To Reproduce**
See Image Above

**Expected behavior**
The automation to run every minute(for testing 1 minute, production 10 minutes)

**Home Assistant version (if applicable):** 
![image](https://github.com/fronzbot/blinkpy/assets/479263/843b50a7-feb7-4e54-9566-35da984b17ff)

**Log Output/Additional Information**
If using home-assistant, please paste the output of the log showing your error below.  If not, please include any additional useful information.

```
PASTE LOG OUTPUT HERE
```
2024-05-30 14:52:51.887 ERROR (MainThread) [frontend.js.latest.202405011] Failed to format translation for key 'component.blink.services.save_recent_clips.description' in language 'en'. Error: The intl string context variable "name" was not provided to the string "Saves all recent video clips to local directory with file pattern "%Y%m%d_%H%M%S_{name}.mp4"."

**Comment by hanor-git** [comment]
Hi, same error for me

**Comment by mkmer** [comment]
@blthlt try using the entity rather than the device for this.  The on I have working looks like this:
![image](https://github.com/fronzbot/blinkpy/assets/7760516/8001c745-7d34-4fc0-9cb2-59931d6262d5)
Also make sure your directory is in the resources.
The translation error has nothing to do with the saving problem.
